# Generated by Django 5.2.5 on 2025-08-29 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientrecipe',
            name='unit_of_measure',
            field=models.CharField(default='kg', max_length=50),
            preserve_default=False,
        ),
    ]
